---
title: "KeycloakをIdPにしてSpring Security OAuth 2.0 Login/Client を試してみる"
date: 2020-07-20T18:54:23Z
draft: true
tags:
  - spring-boot
  - spring-security
  - oauth
  - oidc
---

== はじめに

Spring Boot で Spring Security OAuth 2.0 https://docs.spring.io/spring-security/site/docs/5.3.3.RELEASE/reference/html5/#oauth2login[Login] / https://docs.spring.io/spring-security/site/docs/5.3.3.RELEASE/reference/html5/#oauth2client[Client] を利用する手順をまとめます。

また、認可サーバ(IdP)にはローカルで立てたKeycloakを用いますのでそちらのセットアップ手順も記載します。

補足事項: Keycloakは https://www.keycloak.org/docs/latest/securing_apps/#java-adapters[クライアントライブラリ]も提供しており(Spring系のもので言うと、Spring Securityを利用しないもの、Spring Securityを利用するもの、の2種があるようです。詳細は https://github.com/keycloak/keycloak-quickstarts[実装サンプル]にあります)、Keycloakを利用するのであればそちらを使うのが良さそうです。
ただし、今回は、最終的にKeycloakをIdPとして使うわけではなく、仮に利用しているだけなので、それらは用いず、Spring Securityの汎用機能 https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2client[Spring Security OAuth 2.0 Client] を利用します。

== Keycloakセットアップ

参考: https://www.keycloak.org/getting-started[Getting Started] > https://www.keycloak.org/getting-started/getting-started-zip[Keycloak on OpenJDK]


=== ダウンロードと展開

https://www.keycloak.org/downloads からスタンドアロンサーバをダウンロードして展開します(これはWildFlyベースのサーバのようです)。本エントリ記載時点では https://downloads.jboss.org/keycloak/10.0.2/keycloak-10.0.2.tar.gz です。


=== Keycloak起動

続いて、Keycloakを起動します(この起動方法がまさにWildFlyですね)。

[source,bash]
----
./bin/standalone.sh
----

=== admin ユーザ作成

adminユーザ未作成状態で http://localhost:8080/auth/ へアクセスすると、adminユーザのユーザ名とパスワード入力を促されます。

ここではユーザ名、パスワードとも `admin` とすることにします。

|===
|Username|admin
|Password|admin
|===

**Create** ボタンを押すと上記で入力したadminユーザが作成されます。

http://localhost:8080/auth/admin/[Administration Console] リンクを押して次の画面に進みます。

=== realm作成

Administration Console を開くと、左上に "Master" というプルダウンメニューのようなものがあると思います。

ここにマウスカーソルを合わせると "Add realm" というボタンが表れるのでそれを押します。そうすると http://localhost:8080/auth/admin/master/console/#/create/realm へ遷移します。

Nameに `myrealm` と入力ｋし、 Create ボタンを押します。

|===
|Name|myrealm
|===

作成が完了すると Administration Console 画面に戻ります。
このとき、左上のrealm名画先ほど作成した "Myrealm" になっていると思います。

続いてこの画面からユーザを作成します。

=== ユーザ作成

画面左のメニュー http://localhost:8080/auth/admin/master/console/#/realms/myrealm/users[Users] を選択し、 "Add user" ボタンを押します。

Usernameに `myuser` を、それ以外の項目も適当に埋め "Save" ボタンを押します。

|===
|Username|myuser
|Email|\myuser@example.com
|First Name|my-firstname
|Last Name|my-lastname
|===

ユーザ作成が完了したら、続いてパスワード設定を行います。
画面上部の "Credentials" タブをクリックして開き、パスワードを設定します。ここではユーザ名と同じ `myuser` としました。
また、"Temporary"を `OFF` にしておきます(ONだと初回ログイン時パスワード変更を求められます)。

|===
|Password|myuser
|Password Confirmation|myuser
|Temporary|OFF
|===

そして、 "Set Password" ボタンを押しパスワード設定完了です。

=== クライアント登録

ここでいう "クライアント" というのはOAuth2.0でいうところの認可クライアント、OIDCでいうところのRPです。

画面左のメニュー http://localhost:8080/auth/admin/master/console/#/realms/myrealm/clients[Clients] をクリックします。

続いて画面右の http://localhost:8080/auth/admin/master/console/#/create/client/myrealm[Create]ボタンを押します。

この画面で次のように入力して、 "Save" ボタンを押します。

|===
|Client ID|myclient
|Client Protocol| openid-connect (デフォルトのまま)
|Root URL| (空のままでOK)
|===

クライアント作成が完了したら続いてこのクライアント設定画面で 次の通り設定変更し "Save" ボタンを押します。

|===
|Access Type|confidential
|Valid Redirect URL| \http://localhost:8081/*
|===

上記の通り Access Type を `confidential` に設定すると、この画面上部に "Credentials" タブが表示されます。
このタブで client-secret を確認できます。

これで認可サーバであるKeycloak側の設定は終了です。

続いて、この認可サーバを利用するクライアントをSpring Bootで作っていきます。

== クライアント(Spring Boot)設定

はじめに、で記載した通り、 Spring Securityの機能を利用します。

Spring Boot では、 https://start.spring.io/ で "OAuth 2.0 Client" を選ぶことで追加される https://github.com/spring-projects/spring-boot/blob/v2.3.1.RELEASE/spring-boot-project/spring-boot-starters/spring-boot-starter-oauth2-client/build.gradle[`spring-boot-starter-oauth2-client`] を用いることになります。

余談ですが(&結構何回も書いてきていますが)、 https://spring.io/projects/spring-security-oauth[`spring-security-auth2`] と、今回利用する `spring-security-oauth2-client` は名前が似ているだけで別系統のライブラリです(そして前者はdeprecatedです)。

