[[main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 1

[[main]]
identifier = "docs"
name = "Docs"
url = "/docs"
weight = 2

[[main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 3

[[main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yukihane"
weight = 4
