[[main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 1

[[main]]
identifier = "docs"
name = "Docs"
url = "/docs"
weight = 2

[[main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 3

[[main]]
identifier = "profile"
name = "Profile"
url = "https://github.com/yukihane/resume/blob/main/README.md"
weight = 4
