---
title: "Jacksonでコンストラクタを利用してデシリアライズ"
date: 2022-03-12T14:12:33+09:00
draft: false
tags:
    - jackson
---

(今回のコード: https://github.com/yukihane/hello-java/tree/main/jackson/jackson-deserialize-by-constructor )

Jackson は引数なしコンストラクタが必要、という話は昔は正しかったのですが、今は必須ではありません。

* `@JsonCreator` を付与することでそのコンストラクタを使ってデシリアライズするように指示できます。
** コンストラクタが1つしか無い場合は省略できます。
* JSON プロパティと Java フィールドのマッピングは `@JsonProperty` で行えます。
** https://github.com/FasterXML/jackson-modules-java8/tree/2.14/parameter-names[`jackson-module-parameter-names`] を利用すると、メソッドシグネチャのパラメータを利用してマッピングできるので、この設定を省略できます。
*** ちなみに、この機能は Jackson 3.x では本体(`jackson-databind`)に統合されるようです。(2.x は Java7 以前もサポート対象にしているので Java8 以降の機能は切り出しているみたいです)

というわけで、今 Jackson を使うなら、次のようにすれば良いです:

[source,java]
----
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import lombok.RequiredArgsConstructor;
import lombok.Value;

public class JavaMain {
    public static final String JSON_TEXT = "{\"name\": \"Bob\", \"age\": 30 }";

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper om = new ObjectMapper();
        om.registerModule(new ParameterNamesModule());

        Person person = om.readValue(JSON_TEXT, Person.class);
        System.out.println(person);
    }
}

@Value
// ちなみに Lombok を使っていて自動生成されるコンストラクタにアノテーションを付与したい場合は:
// @RequiredArgsConstructor(onConstructor = @__(@JsonCreator))

class Person {
    String name;
    int age;
}
----

Java17 なら `record` class に置き換えられるので、 `Person` はもはや Lombok を利用しなくとも簡単に書けるようになりました:

[source,java]
----
record Person(String name, int age) {
}
----

コンパイルオプションに、メソッドシグネチャに仮引数名を残す設定 `-parameters` を追加する必要もあります。

これは、 `maven-compiler-plugin` の https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#parameters[`parameters`] を `true` にすることで実現できます。
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.10.1</version>
    <configuration>
        <parameters>true</parameters>
    </configuration>
----

プラグインのバージョンが古い(`3.6.2` 未満)場合はこのオプションが無いので、代わりに https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerArgs[`compilerArgs`] で設定します。
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.5.1</version>
    <configuration>
        <compilerArgs>
            <arg>-parameters</arg>
        </compilerArgs>
    </configuration>
    ...
----

関連:
* link:{{< relref "/blog/202002/20/spring-boot-compiler-parameters" >}}[Spring Bootでは -parameters オプションは有効化されている ]
* link:{{< relref "/blog/202110/18/java17-record-on-spring-mvc" >}}[Spring MVC で Java17 record を試してみる ]
