---
title: "GitHub Actions を使って GitHub Pages を定期更新する"
date: 2021-06-06T12:50:13Z
draft: false
tags:
  - github
---

これまで GitHub Actions を使ったことがなかったのですが、

* https://ja.stackoverflow.com/q/76279/2808[GitHub Pagesの更新を自動化したい - スタック・オーバーフロー]

という質問を見かけ、丁度よいお題だと思ったのでこれを実現してみることにしました。

== リポジトリ作成とコードコミット

まず、GitHub Pages用のリポジトリとそれを定期更新するためのプログラムを管理するリポジトリの2つを用意します。これらは1つのリポジトリにまとめてしまえると思いますが、冒頭の質問者の環境はそうでは無さそうだったので今回は別々にしました。

なお、私は既に個人用に GitHub Pages を利用しているので、別途 https://github.com/hello-github-actions/[hello-github-actions] という https://docs.github.com/ja/organizations/collaborating-with-groups-in-organizations/about-organizations[Organization] を作成して、そちらに上記2リポジトリを作成しました。

* GitHub Pages 用: https://github.com/hello-github-actions/hello-github-actions.github.io[hello-github-actions/hello-github-actions.github.io]
* 更新プログラム管理用: https://github.com/hello-github-actions/updater[hello-github-actions/updater]

更新プログラムは https://github.com/hello-github-actions/updater/blob/main/src/main/java/com/github/yukihane/actions/App.java[こんな感じ] のもので、スタック・オーバーフローのRSSを取得して `public` ディレクトリにhtmlで書き出すものです。 この `public` ディレクトリ以下を GitHub Pages に表示する設定を行っていきます。

== Deploy key 設定

https://github.com/peaceiris/actions-gh-pages[GitHub Actions for GitHub Pages] というアクションを利用して更新を行います。

このページの https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository[Deploy to external repository external_repository] に記載されている機能を用いるために、 Deploy key の設定を行っておきます。

=== 鍵生成

まず、 https://docs.github.com/ja/developers/overview/managing-deploy-keys#%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97-2[デプロイキーの管理 > デプロイキー > セットアップ] の手順通り、 https://docs.github.com/ja/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key[`ssh-keygen` コマンドでキーを生成]します。
[source]
----
ssh-keygen -t ed25519 -C "your_email@example.com"
----

=== GitHub Pages リポジトリへ deploy key として公開鍵を登録

続いて、公開鍵を GitHub Pages のリポジトリに Deploy key として登録します。

リポジトリの Settings > Deploy keys > Add deploy key ボタンから登録できます。
上記した私のリポジトリの場合は

* https://github.com/hello-github-actions/hello-github-actions.github.io/settings/keys/new

から登録することになります。
 **Allow write access** のチェックを入れます。Title は何でも良いようです。

=== 更新プログラム リポジトリへ repository secret として秘密鍵を登録

その後、秘密鍵を更新プログラムリポジトリのシークレットとして登録します。

リポジトリの Settings > Secrets > New repository secret ボタンから登録できます。 
私のリポジトリの場合は

* https://github.com/hello-github-actions/updater/settings/secrets/actions/new

から登録することになります。
Name は後で GitHub Actions スクリプトから変数名として利用するので覚えておいてください。今回のサンプル実装では https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository[リファレンスのサンプル]と同じく **ACTIONS_DEPLOY_KEY** という名前に設定しています。

== GitHub Actions 設定

更新プログラムを定期的に実行したいので、更新プログラムリポジトリに設定を行います。

`.github/workflows` に ymlファイルを作成します。名前は何でも良いようなので今回は `update.yml` としました。

記載内容は

* https://docs.github.com/ja/actions

などを参考にし、結果的に次のようになっています。

* https://github.com/hello-github-actions/updater/blob/main/.github/workflows/update.yml

前述した通り、 **ACTIONS_DEPLOY_KEY** という名前を変数として用いています。
