---
title: "Kotlin の似たようなクラス"
date: 2022-06-11T11:55:44+09:00
draft: false
- tags:
  - kotlin
---

(昔書きかけて完成していないっぽいですが、置いておいても忘れるだけなのでcommitしてしまいます)

link:{{< relref "/blog/content/blog/202206/11/value-object.adoc" >}}[value object] のことを調べていたら、 Kotlin にぱっと見似たような異なるクラス定義方法があることに気付いたので、それらについてまとめておきます。

== data classes

* https://kotlinlang.org/docs/data-classes.html

Kotlin プログラマなら馴染みのあるクラスだと思うのでここで詳しく説明する必要はないでしょう。

`equals()`(及び `hashCode()`)を自動生成する性質などを鑑みると、(更に言うと、 `copy()` を備えていることから immutable な) value object(https://ja.wikipedia.org/wiki/Value_object[Wikopedia]) を構築するためのクラスと見做して差し支えないと考えます(もちろん `var` でプロパティを宣言することもできますし、 `equals()` もオーバーライドできはしますが)。

Java の https://docs.oracle.com/javase/specs/jls/se17/html/jls-8.html#jls-8.10[`record classes`] や、 Lombok の https://projectlombok.org/features/Value[`@Value`] (+ https://projectlombok.org/features/With[@With]) と同じ方向性のクラスですね。 

(ちなみに `data class` に https://youtrack.jetbrains.com/issue/KT-42430[`@JvmRecord` アノテーションを付与すると Java の `record` としてコンパイルされる]みたいですね。)


== inline classes

* https://kotlinlang.org/docs/inline-classes.html
* https://github.com/Kotlin/KEEP/blob/master/proposals/inline-classes.md

1.5.0 から正式導入されました(ので、 Kotlin in Action で入門した私は知らなかった...)。
次節で説明する value-based classes のサブセット。
[source]
----
@JvmInline
value class Password(val s: String)
----
のように書きます。 +
(value-based classes のサブセットである inline classes 、なのに `value` というキーワードで定義するのが混乱を招きそう...)



== value classes (value-based classes)

* https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md

