---
title: "Kotlin in Action (Kotlin イン・アクション) 読書メモ"
date: 2022-01-01T14:17:30+09:00
draft: false
tags:
  - kotlin
---

== Kotlin 関連書籍について

書籍 https://book.mynavi.jp/ec/products/detail/id=78137[Kotlinイン・アクション] を読んでいます。

2022 年 1 月現在の https://kotlinlang.org/docs/releases.html#release-details[Kotlin 最新バージョン] が `1.6.10` であるのに対し、本書が解説しているのは `1.0` のようなので、役に立つのかな…と当初は考えていましたが、今のところ、これは駄目だ、というところは無さそうです。
(気になる人はドキュメントの "Earlier versions" (https://kotlinlang.org/docs/whatsnew11.html[このあたり]) で新機能について説明があります)

他方、 Amazon Kindle の Unlimited で提供されている Kotlin 関連書籍も読んでみましたが、全てイマイチでした。素直にお金出して Kotlin イン・アクション買いましょう。

Java 開発経験と、あと何かもう少し関数型言語的な機能(TypeScript とか Rust 程度)が有る言語に触れたことがあれば、流し読みで理解できて、読み切ればレビュー指摘受けながら Kotlin 開発できるようになってそうです。

また、公式リファレンス(のコア部分)を日本語訳されている方がいらっしゃるようです:

* https://dogwood008.github.io/kotlin-web-site-ja/docs/reference/

== 実行環境セットアップ

実行するだけならオンラインで playground が用意されています:

* https://play.kotlinlang.org/

が、 Java との相互運用的なところも確認したいと思うので、最初からローカルに環境を作っておきます。

https://sdkman.io/[SDKMAN!] で JDK17 と Gradle をインストール。
Windows であれば SDKMAN! の代わりに https://scoop.sh/[Scoop] で双方インストールできるでしょう。
Scoop のインストールについては https://zenn.dev/yukihane/articles/fb52d049da587c[こちら] で触れています。

IDE は https://www.jetbrains.com/ja-jp/idea/download/[IntelliJ IDEA] の Community 版を利用。

IntelliJ はショートカットキーが独特なので初めてだと戸惑いますが、取り敢えず `Ctrl` + `Shift` + `A` でコマンドパレット、だけ覚えておけば何とかなるでしょう。

== プロジェクト作成

`gradle init` コマンドで Kotlin プロジェクト雛形作成できます。その上で、次の2点を編集します:

* https://github.com/yukihane/hello-kotlin/blob/88ed0819e6db9cc54bab3c293d385e98b3f587a1/kotlin-in-action/chxx/app/build.gradle.kts#L11[kotlin プラグイン最新化] (本文章記載時点では https://kotlinlang.org/docs/releases.html[`1.6.10`])
* https://github.com/yukihane/hello-kotlin/blob/88ed0819e6db9cc54bab3c293d385e98b3f587a1/kotlin-in-action/chxx/app/build.gradle.kts#L39-L43[javaツールチェインで Java バージョン 17 を指定]

[source]
.app/build.gradle.kts
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
}
----

[source]
.app/build.gradle.kts
----
java {
    toolchain {
      languageVersion.set(JavaLanguageVersion.of(17))
    }
}
----

こちらの記事を参考にしました:

* https://blog1.mammb.com/entry/2021/12/06/090000[イマドキの Kotlin アプリケーション向け build.gradel.kts - A Memorandum]
* https://blog.jetbrains.com/kotlin/2021/11/gradle-jvm-toolchain-support-in-the-kotlin-plugin/[Gradle JVM Toolchain Support in the Kotlin Plugin | The Kotlin Blog]

== 読書メモ(随時追加)

=== 6.1.11 null 許容性の区別と Java (p.198, リスト 6.16)

* https://github.com/yukihane/hello-kotlin/blob/main/kotlin-in-action/chxx/app/src/main/kotlin/ch06/6_1_11.kt

書籍では、詳細なメッセージを伴った `IllegalArgumentException` が送出されるとありますが、実際には単純に `NullPointerException` が送出されました。

1.4.0 の次の変更が影響していそうです:

* https://kotlinlang.org/docs/whatsnew14.html#unified-exception-type-for-null-checks[Unified exception type for null checks] - What's new in Kotlin 1.4
