---
title: "UbuntuでKindle for PCを使う"
date: 2020-07-26T01:57:49Z
draft: false
---

書きかけのページです。次のリンク先が参考になります。

* https://qiita.com/giwagiwa/items/d2e447af5225c1ce9800

Ubuntu16.04上で、PlayOnLinxで管理されたWine環境でKindle for
PCを動作させる手順です。

[[wine_インストール]]
== Wine インストール

PlayOnLinuxを動作させるのに先立ってWineが必要らしいのでインストールします。
なお**このWineはKindleを動作させるものではない**ので、最新安定版をインストールしておけば良いようです。
(後述しますが、**Kindleを動作させるWine**は相性問題で必ずしも最新版が良いとは限らないようです。)

'''''

古い記事では ppa:wine/wine-builds
を使用するよう書かれているが、これは既にdeprecatedです(リポジトリ追加時に警告も出る)。

https://launchpad.net/~wine/+archive/ubuntu/wine-builds

____
!!! PLEASE NOTE THAT THIS REPOSITORY IS DEPRECATED !!!

For more information, please see:

`   `https://www.winehq.org/pipermail/wine-devel/2017-March/117104.html[`https://www.winehq.org/pipermail/wine-devel/2017-March/117104.html`]

The following commands can be used to add the new repository:

`   wget `https://dl.winehq.org/wine-builds/Release.key[`https://dl.winehq.org/wine-builds/Release.key`] +
`   sudo apt-key add Release.key` +
`   sudo apt-add-repository '`https://dl.winehq.org/wine-builds/ubuntu/[`https://dl.winehq.org/wine-builds/ubuntu/`]`'`
____

というわけで、ここに書かれているとおり、代わりに新しいリポジトリを用います。
…と、以前はそれでよかったのですが、2018年末、ここから更に公開鍵が変わったようなので、次のコマンドを実行する必要があります(https://wiki.winehq.org/Ubuntu[参考])。

....
wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo apt-key add winehq.key
....

リポジトリを追加します。Ubuntuのバージョンごとに異なりますのでhttps://wiki.winehq.org/Ubuntu[リンク先]を参照してください。下は18.04の例です。

....
sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
....

リポジトリを追加したら、次のコマンドでWineのstable版をインストールします。

....
sudo apt-get install --install-recommends winehq-stable
....

[[playonlinux_インストール]]
== PlayOnLinux インストール

Ubuntuのリポジトリにも playonlinux
は存在するが、オフィシャルサイトにある方がバージョンが新しかったのでそちらを用いることにします。

* https://www.playonlinux.com/en/download.html

に書かれているとおりにインストール。`playonlinux_xenial.list`の部分はバージョンによって異なるので適宜読み替えます。

....
wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
sudo wget http://deb.playonlinux.com/playonlinux_xenial.list -O /etc/apt/sources.list.d/playonlinux.list
sudo apt-get update
sudo apt-get install playonlinux
....

なお、このページに以下の通り書かれているのが確認できるはず。実際にwineをインストールせずにplayonlinuxを起動するとwineが必要という警告ダイアログが出ます。

____
Ubuntu Precise (and superior) users : You must install the package
wine:i386 to get PlayOnLinux working
____

== インストールするWineとKindleのバージョンの選定

冒頭でも少し触れましたが、WineとKindle for
PCは最新版のほうが良いとは限らず、相性があるようです。
次のページに動作検証結果が書かれています。

* https://appdb.winehq.org/objectManager.php?sClass=application&iId=10597

_Latest Rating_ の項目が Platinum か Gold
になっているものを選んでおけばよいかと思います。
今回はPlatinumとされている Kindle for PCのバージョン 1.17.x , Wine
のバージョン 2.15 を選ぶこととしました。

[[kindle_for_pc.co.jp対応版_ダウンロード]]
== Kindle for PC(.co.jp対応版) ダウンロード

Kindle for
PCについて、PlayOnLinuxからダウンロードはできるものは.co.jpアカウントでログイン出来ないようですので、別途入手します。
参考にした https://qiita.com/giwagiwa/items/d2e447af5225c1ce9800[こちら]のページでは https://kindle-for-pc.en.uptodown.com/windows[このサイト]から入手していました。

== PlayOnLinxにKindle環境を構築

=== PlayOnLinux起動

`playonlinux` コマンドで起動できます。

=== Kindleを動作させるWineのインストール

ツール > Wineのバージョンを管理
メニューを選択し、前述の通り決定したバージョン 2.15
をインストールします。

[[kindle_for_pc_のインストール]]
=== Kindle for PC のインストール

ファイル > インストール
メニューを選択します。(本来ならここでインストール可能なアプリ一覧が表示されるようですが、私が今回インストールしたバージョンでは読み込み中表示のまま止まっています)

画面下部の"_リストにないプログラムをインストールする_"を選択します。

"_Install a program in a new virtual drive_"を選択します。

好きな名前を入力します。(私は _for_kindle_ と入力しました)

"_Use another version of Wine_" と "_Configure Wine_"
にチェックを入れます。

Kindle for PCを動作させるWineのバージョンである _2.15_ を選択します。

"_32bits windows installation_" を選択します。

MonoインストールとGeckoインストールを促されますが、両方キャンセルします。

"アプリケーション"タブの "Windowsバージョン" を *Windows 8.1*
に設定します。

install file の選択に置いて、先にダウンロードしておいた Kindle for
PCのインストーラexeを指定します。

== 未解決の問題

Kindle for PCアプリケーション上の日本語が豆腐になっている。

