---
title: "Ubuntuその他設定"
date: 2020-07-26T02:03:01Z
draft: false
---

[[ubuntu18.04で入力ソース切り替え日本語英語切り替えを_shiftspaceに変更する]]
== Ubuntu18.04で入力ソース切り替え(日本語/英語切り替え)を Shift+Spaceに変更する

設定画面からShift+Spaceに変更すると、逆方向の切り替えが同期してSpaceになってしまい使い物にならない。
次のコマンドで変更できる。

....
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Shift>space']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "[]"
....

== ホームフォルダの「ダウンロード」ディレクトリ名などを英語に変更する

....
LANG=C xdg-user-dirs-gtk-update
....

== Ubuntu18.04で画面端にウィンドウを持っていっても勝手にリサイズされないようにする

....
gsettings set org.gnome.mutter edge-tiling false
....

== Ubuntu18.04へアップグレードしたらログイン画面がループする(Xが起動しない)

次のコマンドでパッケージの再インストールを行ったところ起動するようになった。

X関連のパッケージをpurge。

....
sudo apt-get purge nvidia-* ubuntu-desktop gdm3
....

再起動。

....
sudo reboot
....

gdm3アンインストール時、gdmユーザが削除できない旨のメッセージが出ていたのでそれを削除。

....
sudo userdel gdm
....

ubuntu-desktopインストール(gdm3もインストールされる)。

....
sudo apt-get install ubuntu-deskitop
....

nvidia driver install

....
sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get install nvidia-driver-410
....

== fontをインストールする

Eclipse上の表示がおかしいので別のfontを用いることにした。
今回インストールしたのは https://github.com/miiton/Cica/releases[Cikaフォント]。

. .ttf ファイルを /usr/local/share/fonts ディレクトリにコピーする
. `sudo fc-cache -fv` コマンドを実行する

